"""
services/document_assembly.py
================================

Assembles a DRAFT .docx for a document type from document_catalog.py,
populated with facts already sitting in the case's own workspace tables.

THE ONE RULE THIS FILE DOES NOT BREAK:
No case citation is ever generated by this module. The Argument section
lists ONLY authorities that already exist in this project's own
legal_authorities table AND have filing_ready=1 — meaning they already went
through the existing legal_safety.py verification workflow (primary source
checked, proposition checked, pinpoint checked, current-law checked, no
unaddressed negative treatment). Anything else becomes a
"[VERIFY CITATION — attorney/researcher to add]" placeholder. This module
has no path to inserting a citation Claude or this app made up, because it
doesn't write citation text at all — it only copies rows a human already
verified through the app's own pipeline.

Every generated document opens with a DRAFT banner, closes with a
pre-filing checklist, and is meant to be reviewed — ideally by a licensed
attorney — before it goes anywhere near a court.
"""

from __future__ import annotations

from datetime import date
from io import BytesIO

from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from . import document_catalog

DRAFT_RED = RGBColor(0xB0, 0x1E, 0x1E)
INK = RGBColor(0x07, 0x10, 0x1D)
MUTED = RGBColor(0x55, 0x55, 0x55)


def _set_page(doc):
    section = doc.sections[0]
    section.page_width = Inches(8.5)
    section.page_height = Inches(11)
    section.left_margin = Inches(1)
    section.right_margin = Inches(1)
    section.top_margin = Inches(1)
    section.bottom_margin = Inches(1)


def _add_page_number_field(paragraph):
    run = paragraph.add_run()
    fld1 = OxmlElement("w:fldChar"); fld1.set(qn("w:fldCharType"), "begin")
    instr = OxmlElement("w:instrText"); instr.set(qn("xml:space"), "preserve"); instr.text = "PAGE"
    fld2 = OxmlElement("w:fldChar"); fld2.set(qn("w:fldCharType"), "end")
    run._r.append(fld1); run._r.append(instr); run._r.append(fld2)


def _header_footer(doc):
    section = doc.sections[0]
    header_p = section.header.paragraphs[0]
    header_p.text = ""
    r = header_p.add_run("DRAFT — NOT REVIEWED BY COUNSEL — DO NOT FILE WITHOUT ATTORNEY REVIEW")
    r.bold = True
    r.font.size = Pt(9)
    r.font.color.rgb = DRAFT_RED
    header_p.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_p = section.footer.paragraphs[0]
    footer_p.text = ""
    footer_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = footer_p.add_run("DRAFT — Page ")
    r.font.size = Pt(8); r.font.color.rgb = MUTED
    _add_page_number_field(footer_p)
    r2 = footer_p.add_run(f" — generated {date.today().isoformat()}, unreviewed")
    r2.font.size = Pt(8); r2.font.color.rgb = MUTED


def _caption(doc, case, charge):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r = p.add_run((case["court_name"] or "[COURT NAME — confirm]").upper())
    r.bold = True; r.font.size = Pt(12)

    p2 = doc.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r2 = p2.add_run(case["case_name"] or "[CASE NAME]")
    r2.bold = True; r2.font.size = Pt(12)

    p3 = doc.add_paragraph()
    p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    line = f"Case No. {case['case_number'] or '[CASE NUMBER — confirm]'}"
    if charge is not None:
        line += f"  ·  {charge['statute'] or '[STATUTE]'} — {charge['charge_name']}"
        if charge["count_number"]:
            line += f", Count {charge['count_number']}"
    p3.add_run(line).font.size = Pt(10)
    doc.add_paragraph()


def _notice_box(doc, text, color=DRAFT_RED):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    r = p.add_run(text)
    r.italic = True
    r.font.size = Pt(9)
    r.font.color.rgb = color
    return p


def _heading(doc, text):
    p = doc.add_heading(level=2)
    run = p.add_run(text)
    run.font.color.rgb = INK
    return p


def _placeholder(doc, text):
    p = doc.add_paragraph()
    r = p.add_run(f"[{text}]")
    r.italic = True
    r.font.color.rgb = MUTED
    return p


def _bullet(doc, text, style="List Bullet"):
    doc.add_paragraph(text, style=style)


def _facts_section(doc, db, case_id, case_type):
    assertions = db.execute(
        "SELECT * FROM case_factual_assertions WHERE case_id=? ORDER BY id",
        (case_id,),
    ).fetchall()
    if not assertions:
        _placeholder(doc, "No factual assertions entered yet for this case. Add them in the case workspace, then regenerate this draft.")
        return
    for a in assertions:
        tag = "VERIFIED" if a["verification_status"] == "VERIFIED" else "UNVERIFIED"
        _bullet(doc, f"[{tag}] {a['assertion_text']}")
    _notice_box(doc, "Assertions tagged UNVERIFIED above are as-reported, not confirmed against the record. Confirm each against a transcript, report, or exhibit before this document is filed.", color=MUTED)


def _procedural_history_section(doc, case):
    p = doc.add_paragraph()
    p.add_run(f"Proceeding type: {case['proceeding_type']}. Current posture: {case['procedural_posture'] or '[confirm current posture]'}.")
    _placeholder(doc, "Add trial court disposition, sentence, and any direct-appeal or prior post-conviction history here.")


def _grounds_section(doc, db, case_id):
    issues = db.execute(
        """SELECT cdi.*, dic.issue_name FROM case_defense_issues cdi
           JOIN defense_issue_catalog dic ON dic.issue_code = cdi.issue_code
           WHERE cdi.case_id=? ORDER BY cdi.id""",
        (case_id,),
    ).fetchall()
    if not issues:
        _placeholder(doc, "No defense issues logged yet. Add them in the Defense Intelligence workspace, then regenerate this draft.")
        return
    for i, issue in enumerate(issues, start=1):
        p = doc.add_paragraph()
        p.add_run(f"Ground {i}: {issue['issue_name']}").bold = True
        if issue["factual_basis"]:
            doc.add_paragraph(issue["factual_basis"])
        doc.add_paragraph(f"Factual support status: {issue['factual_support_status']}  ·  Authority research status: {issue['authority_status']}  ·  Motion readiness: {issue['motion_readiness']}")


def _argument_section(doc, db, jurisdiction_code, guidance):
    _notice_box(doc, guidance, color=MUTED)
    authorities = db.execute(
        """SELECT title, citation, court_name, decision_date, proposition_text
           FROM legal_authorities WHERE jurisdiction_code=? AND filing_ready=1
           ORDER BY title""",
        (jurisdiction_code,),
    ).fetchall() if jurisdiction_code else []
    if authorities:
        note_p = doc.add_paragraph()
        note_p.add_run("Filing-ready verified authorities currently on file for this jurisdiction (confirm each is actually relevant to this specific claim before citing it):").italic = True
        for a in authorities:
            _bullet(doc, f"{a['title']}, {a['citation']}" + (f" — {a['proposition_text']}" if a["proposition_text"] else ""))
    else:
        _placeholder(doc, "No filing-ready verified authorities on file yet for this jurisdiction. Research and verify authority through the Verification Workbench before citing anything here — do not insert an unverified citation.")
    _placeholder(doc, "Apply the standard above to the facts stated earlier. Write the actual argument here — this tool does not generate persuasive legal argument.")


def _checklist_page(doc, entry):
    doc.add_page_break()
    _heading(doc, "Pre-Filing Checklist")
    _notice_box(doc, "Nothing above this checklist has been reviewed by an attorney. Do not file this document until every item below is confirmed.")
    doc.add_paragraph()
    doc.add_paragraph(f"Governing rule: {entry['rule_note']}")
    doc.add_paragraph(f"Timing/deadline: {entry['deadline_note']}")
    doc.add_paragraph()
    req_p = doc.add_paragraph(); req_p.add_run("Required attachments:").bold = True
    for a in entry["required_attachments"]:
        _bullet(doc, a, style="List Bullet")
    doc.add_paragraph()
    close_p = doc.add_paragraph(); close_p.add_run("Closing requirements:").bold = True
    for c in entry["closing_requirements"]:
        _bullet(doc, c, style="List Bullet")
    doc.add_paragraph()
    for item in [
        "Every UNVERIFIED assertion above has been confirmed or removed",
        "Every [VERIFY CITATION] placeholder has been replaced with a verified, on-point authority",
        "Court rule/format requirements (page limits, font, spacing) confirmed against the current local rule",
        "Filing deadline recalculated and confirmed for this specific case",
        "Reviewed by a licensed attorney",
    ]:
        _bullet(doc, item, style="List Bullet")


def build_docx(db, case, charge, doc_type_key: str) -> BytesIO:
    entry = document_catalog.get(doc_type_key)
    if not entry:
        raise ValueError(f"Unknown document type: {doc_type_key}")

    doc = Document()
    _set_page(doc)
    _header_footer(doc)

    _notice_box(doc, "DRAFT SCAFFOLD — GENERATED BY JUSTICE GATEWAY, NOT REVIEWED BY AN ATTORNEY. This is legal information organized into a document shape, not a finished filing. See the Pre-Filing Checklist at the end before this goes anywhere near a court.")
    doc.add_paragraph()

    _caption(doc, case, charge)

    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    tr = title_p.add_run(entry["title"].upper())
    tr.bold = True; tr.font.size = Pt(13)
    doc.add_paragraph()

    for section in entry["sections"]:
        _heading(doc, section["heading"])
        key = section["key"]
        if key == "facts":
            _facts_section(doc, db, case["id"], case["proceeding_type"])
        elif key == "procedural_history":
            _procedural_history_section(doc, case)
        elif key == "grounds":
            _grounds_section(doc, db, case["id"])
        elif key == "argument":
            jurisdiction_code = entry["jurisdiction_code"] or case["jurisdiction_code"]
            _argument_section(doc, db, jurisdiction_code, section["guidance"])
        else:
            _notice_box(doc, section["guidance"], color=MUTED)
            _placeholder(doc, "Draft this section — this tool does not generate persuasive legal argument or new factual claims.")
        doc.add_paragraph()

    _checklist_page(doc, entry)

    buf = BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
